export const SIGN_IN = '/signin'
export const SIGN_UP = '/signup'
export const USER = '/home/user'
//export const HOME = '/home'
//export const ACCOUNT = '/account'
//export const ADMIN = '/admin'
//export const PASSWORD_FORGET = '/pw-forget'
